x = input('Digite algo: ')

print('Tipo Primitivo: {}' .format(type(x)))
print('Somente Espaços: {}' .format(x.isspace()))
print('Número: {}' .format(x.isnumeric()))
print('Alfabético: {}' . format(x.isalpha()))
print('Alfanumérico: {}' .format(x.isalnum()))
print('Maiúsculo: {}' .format(x.isupper()))
print('Minúsculo: {}' .format(x.islower()))
print('Capitalizado: {}' .format(x.istitle()))
